### ISSUE TITLE
[CI] Add automated compliance tasks to pipeline

### ISSUE THREAD

**Issue by pjcollins** [xamarin/Xamarin.Build.AsyncTask#12]
We are missing a handful of compliance tasks on this rep (policheck, credscan) which should be added to the build pipeline.

**Comment by dellis1972** [comment]
@pjcollins is this done now?

**Comment by pjcollins** [comment]
Yeah, I'll close this as fixed as part of https://github.com/xamarin/Xamarin.Build.AsyncTask/pull/16
